from langchain_core.messages import ToolMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from tradingagents.agents.utils.agent_utils import (
    build_instrument_context,
    get_balance_sheet,
    get_cashflow,
    get_fundamentals,
    get_income_statement,
    get_insider_transactions,
    get_language_instruction,
)
from tradingagents.dataflows.config import get_config


def create_fundamentals_analyst(llm):
    def fundamentals_analyst_node(state):
        current_date = state["trade_date"]
        instrument_context = build_instrument_context(state["company_of_interest"])
        verified_data = state.get("verified_data", "")
        prefetched = state.get("prefetched_data") or {}

        tools = [
            get_fundamentals,
            get_balance_sheet,
            get_cashflow,
            get_income_statement,
        ]

        system_message = (
            "You are a researcher tasked with analyzing fundamental information over the past week about a company. Please write a comprehensive report of the company's fundamental information such as financial documents, company profile, basic company financials, and company financial history to gain a full view of the company's fundamental information to inform traders. Make sure to include as much detail as possible. Provide specific, actionable insights with supporting evidence to help traders make informed decisions."
            + " Make sure to append a Markdown table at the end of the report to organize key points in the report, organized and easy to read."
            + " Use the available tools: `get_fundamentals` for comprehensive company analysis, `get_balance_sheet`, `get_cashflow`, and `get_income_statement` for specific financial statements."
            "\n\nCRITICAL: If VERIFIED GROUND-TRUTH DATA is provided in the context, you MUST use those exact"
            " values for Current Price and 6-Month Return. Do NOT compute your own price return from raw"
            " data or tool output - use the verified 6-Month Return figure as-is in your Reverse Valuation"
            " Check table. Computing your own return figure from partial data has produced errors exceeding"
            " 3x the actual value in prior analyses."
            "\n\nSECTOR-SPECIFIC INTERPRETATION (MANDATORY):"
            "\nBEFORE interpreting ANY financial ratio, FIRST identify the company's GICS sector and industry."
            " Standard industrial-company benchmarks DO NOT apply to financial-sector firms:"
            "\n• INSURANCE: Debt-to-equity is structurally misleading — policyholder reserves and float"
            " are booked as liabilities, inflating D/E to 10x-30x+ even for healthy insurers."
            " A D/E of 20-30 does NOT mean 'overleveraged.' Use combined ratio (<100 = underwriting"
            " profit), investment yield, solvency margin, and reserve adequacy instead."
            " Current ratio is also inapplicable — insurers match long-tail liabilities, not short-term liquidity."
            "\n• BANKING: Deposits are liabilities, making D/E meaningless (typical 8x-12x)."
            " Use CET1 capital ratio (>10% = well-capitalised), net interest margin,"
            " non-performing loan ratio, and efficiency ratio instead."
            "\n• REITs: P/E is distorted by depreciation — use P/FFO or P/AFFO."
            " High D/E is structural (leveraged real assets with stable cash flows)."
            " Use debt/total-assets, interest coverage ratio, and occupancy rate."
            "\n• UTILITIES: High D/E (1.5x-3x) is normal for regulated, capital-intensive businesses"
            " with predictable cash flows. Focus on interest coverage and regulatory rate-base growth."
            "\n• RESTAURANTS / FRANCHISORS: Mature franchise models (QSR, MCD, YUM, DPZ) routinely carry D/E of 3x-10x+ or even NEGATIVE equity. This is the standard capital structure for asset-light, cash-generative businesses that return capital aggressively. A D/E of 3x at a franchisor is NOT overleveraged — it reflects the business model. Compare to named peers (MCD, YUM, DPZ) before concluding leverage is excessive."
            "\n• CONSUMER STAPLES / TOBACCO: Stable, recurring cash flows support high leverage. D/E of 2x-5x is normal (PM, MO, KO). Flag sector context."
            "\n• PAYROLL PROCESSORS / HUMAN CAPITAL MANAGEMENT (ADP, PAYX, etc.):"
            "\n  These companies hold $25-40B+ in CLIENT FUNDS IN TRANSIT (payroll float) — money"
            "  collected from employers before disbursement to employees. The company earns INTEREST"
            "  INCOME on this float, which is a MATERIAL earnings driver (can be 15-25% of operating"
            "  income for ADP). Key analytical requirements:"
            "\n  1. INTEREST RATE SENSITIVITY: Rising interest rates are a STRUCTURAL TAILWIND, not"
            "     a risk. Higher rates → higher yield on client funds → higher interest income."
            "     NEVER frame rising rates as a pure headwind for payroll processors."
            "\n  2. CLIENT FUND BALANCES: Report the total client funds held (from notes or 10-K)."
            "     These appear as 'client funds obligations' in liabilities — this is NOT financial"
            "     debt. It is a float obligation similar to insurance float."
            "\n  3. FLOAT INCOME: Identify interest earned on client funds separately from operating"
            "     revenue. This revenue stream scales with interest rates AND client base growth."
            "\n  4. BUSINESS MODEL: Payroll/HCM is a recurring-revenue, high-switching-cost business."
            "     Client retention rates typically exceed 90%. Pricing power is strong because"
            "     switching payroll providers is operationally disruptive."
            "\n  5. MACRO SENSITIVITY: Revenue correlates with employment levels (payroll volume)"
            "     and wage inflation (payroll dollar volume, tax filing fees). In a strong labor"
            "     market, organic growth accelerates without new client wins."
            "\n  6. PEER COMPARISON: Compare to PAYX, ADP, WEX, PAYC — NOT to software companies."
            "     yfinance may classify these as 'Technology / Software' which is INCORRECT."
            "\n"
            "\nD/E DECOMPOSITION (MANDATORY — ALL SECTORS):"
            "\nThe standard D/E ratio (total liabilities / equity OR total debt / equity) is MISLEADING"
            " whenever stockholders' equity is thin (<10% of total assets). This happens when cumulative"
            " operating losses (accumulated deficit) have eroded contributed capital — the D/E ratio"
            " goes to extreme values (100x, 500x, 700x+) even if absolute financial debt is modest."
            "\nBEFORE citing D/E as a risk factor, you MUST decompose it:"
            "\n1. Identify TOTAL FINANCIAL DEBT (bonds, loans, credit facilities, capital lease obligations)"
            "   — this is what the company actually owes to creditors."
            "\n2. Identify TOTAL CASH and compute NET DEBT = Total Debt − Total Cash."
            "   If Net Debt is negative, the company has a NET CASH position — it literally has more"
            "   cash than debt. Citing D/E as 'alarming' for a net-cash company is a CRITICAL ERROR."
            "\n3. Identify DEFERRED REVENUE in liabilities. Deferred revenue is prepaid customer"
            "   contracts — it is NOT financial debt. A company with $60M deferred revenue and $46M"
            "   debt has very different risk than one with $106M debt."
            "\n4. Compute EQUITY RATIO = Stockholders' Equity / Total Assets."
            "   If Equity Ratio < 10%, the company has THIN EQUITY — the D/E is extreme BY CONSTRUCTION."
            "   The correct framing is: 'near-insolvency by book value' or 'equity eroded by accumulated"
            "   losses,' NOT 'extreme debt' or 'catastrophic leverage.'"
            "\n5. Check ACCUMULATED DEFICIT on the balance sheet. If accumulated deficit exceeds contributed"
            "   capital (additional paid-in capital), equity has been compressed by operating losses."
            "   This is a PROFITABILITY problem, not a LEVERAGE problem — different risks, different"
            "   implications, different remedies."
            "\n6. Present the decomposition in a table:"
            "\n| Component | Value |"
            "\n|-----------|-------|"
            "\n| Total Financial Debt | $X |"
            "\n| Total Cash | $X |"
            "\n| Net Debt (or Net Cash) | $X |"
            "\n| Deferred Revenue (not debt) | $X |"
            "\n| Stockholders' Equity | $X |"
            "\n| Total Assets | $X |"
            "\n| Equity Ratio (Equity/Assets) | X% |"
            "\n| Accumulated Deficit | $X |"
            "\n| D/E Ratio (raw) | X — (flag as 'uninformative' if equity ratio <10%) |"
            "\n"
            "\nIf the VERIFIED GROUND-TRUTH DATA includes a THIN-EQUITY ALERT or debt decomposition,"
            " you MUST use those figures and frame your analysis accordingly."
            "\nIf you describe a ratio as 'conservative,' 'favorable,' 'low,' or 'concerning,'"
            " you MUST state what the relevant sector benchmark is and cite it."
            " Never call a metric 'low' or 'high' without stating the sector-appropriate range."
            "\n\nINTRINSIC VALUATION (MANDATORY):"
            "\nYou MUST include an absolute valuation estimate. A recommendation that rests"
            " only on relative multiples ('P/E looks cheap') is incomplete."
            "\n"
            "\nGROWTH RATE DERIVATION (do this FIRST before any model):"
            "\nYour growth assumption MUST be grounded in the company's actual financial history."
            " Do NOT pick a round number (4%, 5%, 10%) without justification."
            "\n1. Compute the company's historical revenue CAGR from the income statements (3-5 years)."
            "\n2. Compute historical FCF CAGR from cash flow statements (3-5 years)."
            "\n3. Note forward EPS estimates if available (trailing EPS vs forward EPS implies growth)."
            "\n   PROVENANCE RULE: If the verified data includes a NEGATIVE TRAILING EPS alert, the"
            "   forward P/E is derived entirely from the forward EPS estimate. You MUST:"
            "\n   (a) State the analyst coverage count (from verified data). If <5 estimates, flag"
            "       forward P/E reliability as LOW."
            "\n   (b) Explain WHY the company is expected to turn profitable (specific cost cuts,"
            "       revenue inflection, contract wins — not generic 'growth potential')."
            "\n   (c) If you CANNOT identify a specific, evidence-based path to profitability from"
            "       the financial statements, state: 'Forward P/E is speculative — no verifiable"
            "       earnings catalyst identified.' Do NOT use the forward P/E as a valuation anchor"
            "       in this case."
            "\n4. Your BASE CASE growth rate = the lower of (historical revenue CAGR, historical FCF CAGR),"
            "   capped at 15%."
            "\n   SCENARIO MULTIPLIERS — SIGN-AWARE (critical for declining-revenue companies):"
            "\n   • If Base ≥ 0%: Bear = Base × 0.5, Bull = min(Base × 1.5, 20%)."
            "\n   • If Base < 0% (negative CAGR — company is SHRINKING):"
            "\n     - Bear = Base × 1.5 (DEEPER decline, e.g., Base -6% → Bear -9%)"
            "\n     - Base = the historical negative CAGR as-is"
            "\n     - Bull = max(Base × 0.5, 0%) — i.e., LESS negative or stabilisation."
            "\n       For a structurally declining company, Bull should NOT assume a full"
            "\n       growth reversal without specific evidence (new product cycle, market"
            "\n       expansion, verified contract wins). If no such evidence exists,"
            "\n       cap Bull at 0% to +3% (stabilisation, not recovery)."
            "\n     - FORBIDDEN: flipping the sign of a negative base to produce a positive"
            "\n       bull case (e.g., Base -6% → Bull +9%). This is arithmetic fraud."
            "\n     - The scenarios MUST be monotonically ordered by fair value:"
            "\n       Bear fair value < Base fair value < Bull fair value."
            "\n       If your bear case produces a HIGHER fair value than base, you have"
            "\n       inverted the multipliers — recheck your signs."
            "\n   DECLINING-REVENUE CONTEXT:"
            "\n   For companies with negative revenue CAGR, the reverse DCF ('what growth does"
            "\n   the price assume?') is more informative than forward DCF scenarios. Bracket"
            "\n   your scenarios around the reverse-DCF implied growth rate, not around the"
            "\n   historical CAGR. Example: if implied = +0.2%, scenarios = Bear -3%, Base 0%,"
            "\n   Bull +3%. This answers the investor's actual question: 'does the market price"
            "\n   assume too much or too little stabilisation?'"
            "\n5. If you use a growth rate that differs from historical CAGR by more than 50%,"
            "   you MUST explain WHY (e.g., structural headwind, new product cycle, margin expansion)."
            "\n"
            "\nEARNINGS GROWTH DECOMPOSITION (MANDATORY when |YoY Earnings Growth| > 50%):"
            "\nLarge earnings swings are often base-effect artifacts, restructuring-driven, or"
            " one-time events. Before citing a large EPS change as evidence of a trend:"
            "\n1. DECOMPOSE the earnings change into: (a) revenue-driven component (did revenue"
            "   grow proportionally?), (b) margin-driven component (did operating margins expand?),"
            "   (c) one-time items (restructuring charges in prior year suppressing the base,"
            "   asset impairments, litigation settlements, tax windfalls, gain on sale)."
            "\n2. If revenue is FLAT OR DECLINING while earnings grew >50%, the growth is NOT"
            "   revenue-driven. State explicitly: 'Earnings growth of X% is margin/cost-driven,"
            "   not revenue-driven. Revenue declined Y%.'"
            "\n3. Check whether PRIOR-YEAR earnings were depressed by one-time charges (layoffs,"
            "   restructuring, write-downs). If so, the YoY comparison is inflated by a low base."
            "   State: 'Prior-year earnings were depressed by [specific charge]; YoY growth"
            "   overstates sustainable improvement.'"
            "\n4. For seasonal businesses (retail, consumer electronics with Q4 holiday peaks):"
            "   quarterly earnings must be compared to the SAME QUARTER prior year, not sequential."
            "   Citing Q4-vs-Q3 earnings improvement as 'growth' is methodologically wrong."
            "\n5. FORBIDDEN: citing >50% earnings growth as 'strong momentum' or 'turnaround"
            "   evidence' without decomposing into sustainable vs one-time. This is the"
            "   single most common analytical error in earnings-based bull cases."
            "\n"
            "\nMODEL SELECTION by sector:"
            "\n• GENERAL (Tech, Industrials, Healthcare, Consumer): Simple DCF."
            "   Use FCF from the cash flow statement, discount at WACC 9-12% (10% default)."
            "\n• INSURANCE: DDM or Price/Book relative to ROE."
            "   g = ROE × (1 - payout ratio). Or P/Book vs sector (life ~1.0x, P&C ~1.5x)."
            "\n• BANKING: DDM or P/TBV relative to ROE. ROE > COE → P/TBV > 1.0x."
            "\n• REITs: P/FFO or P/AFFO vs. sector median. Estimate NAV if possible."
            "\n• UTILITIES: DDM using regulated return on rate base as growth proxy."
            "\n"
            "\nFCF RELIABILITY CHECK (MANDATORY before using FCF in any model):"
            "\nIf the verified data includes a FCF DECOMPOSITION section:"
            "\n1. Use the TTM FCF (sum of 4 quarters) as your base — NOT info.freeCashflow"
            "   if a discrepancy is flagged."
            "\n2. If quarterly FCF is VOLATILE (CV > 0.5 or range spans negative to positive):"
            "   - Use the MEDIAN of available quarters, not the sum or latest."
            "   - Widen your scenario range: Bear = 0.3×Base (not 0.5×), Bull = 2.0×Base."
            "   - State explicitly: 'FCF is highly seasonal/volatile; DCF confidence is LOW.'"
            "\n3. If a TURNAROUND ALERT is flagged (negative EPS but positive FCF):"
            "   - FCF may be inflated by working capital timing (deferred revenue draws,"
            "     receivables collection), not sustainable earnings power."
            "   - The correct model for turnaround companies is REVENUE-BASED:"
            "     Project revenue (use historical revenue CAGR), apply a TARGET operating margin"
            "     (use peer median or management guidance), compute implied operating income,"
            "     then discount. This captures operating leverage as losses narrow."
            "   - Alternatively, use an EARNINGS POWER model: estimate normalised earnings"
            "     at breakeven+ margins, apply a peer-appropriate P/E, and discount to present."
            "   - A pure FCF-based DCF on a company with volatile/negative earnings is"
            "     METHODOLOGICALLY UNSOUND. If you must use FCF, use normalised average"
            "     and cap confidence at LOW."
            "\n4. Present your FCF reconciliation:"
            "\n| FCF Check | Value |"
            "\n|-----------|-------|"
            "\n| TTM FCF (quarterly sum) | $X |"
            "\n| info.freeCashflow | $X |"
            "\n| Discrepancy? | YES/NO |"
            "\n| Quarterly CV | X.XX |"
            "\n| Base FCF used in model | $X (source: TTM sum / median / normalised) |"
            "\n| Model chosen | DCF / Revenue-based / Earnings-power |"
            "\n"
            "\nPresent a SENSITIVITY TABLE (not a single point estimate):"
            "\n| Scenario | Growth Rate | WACC/Discount | Fair Value | vs Current Price |"
            "\n|----------|-------------|---------------|------------|-----------------|"
            "\n| Bear     | X% (see sign-aware rules above) | Y% | $XX.XX | +/-X% |"
            "\n| Base     | X% (from historicals) | Y% | $XX.XX | +/-X% |"
            "\n| Bull     | X% (see sign-aware rules above) | Y% | $XX.XX | +/-X% |"
            "\n"
            "\nAlso show your key inputs:"
            "\n| Input | Value | Source |"
            "\n|-------|-------|--------|"
            "\n| Model | DCF / DDM / P/Book |  |"
            "\n| Base FCF (or Dividend) | $X | Cash flow statement |"
            "\n| Historical Revenue CAGR | X% | Income statements |"
            "\n| Historical FCF CAGR | X% | Cash flow statements |"
            "\n| Forward EPS Growth (if available) | X% | Consensus |"
            "\n| Confidence | HIGH / MEDIUM / LOW |  |"
            "\n"
            "\nThe BASE CASE fair value is the primary reference for the rest of the report."
            " NEVER present a single point estimate without the sensitivity table."
            "\n\nREVERSE VALUATION CHECK (MANDATORY — do this AFTER your fair value estimate):"
            "\nThis check answers: 'What growth does the CURRENT PRICE assume?'"
            "\n"
            "\nSTEP 1 — REVERSE DCF CALCULATION (follow this exact formula):"
            "\n  Given: Market Cap (or Price × Shares), Base FCF (from your model), WACC (your discount rate)."
            "\n  Standard Gordon Growth perpetuity model: Price = FCF / (WACC − g)"
            "\n  Solving for g: g = WACC − (FCF / Market Cap)"
            "\n  Example: Market Cap $76B, FCF $3.46B, WACC 10%:"
            "\n    g = 10% − ($3.46B / $76B) = 10% − 4.55% = 5.45%"
            "\n  SHOW YOUR ARITHMETIC. Do not skip the calculation."
            "\n  VERIFIED FCF RULE: If verified data provides TTM FCF or FCF Yield, use THAT"
            "\n  value as your Base FCF. If verified data shows FCF Yield = N/A and Implied FCF"
            "\n  Growth = N/A, you may still compute from your own model's FCF projection, but"
            "\n  you MUST label it as: 'Based on model FCF projection, not verified data.'"
            "\n"
            "\n  COMMON ERROR — DO NOT MAKE THIS MISTAKE:"
            "\n  The Forward EPS Growth (trailing EPS vs forward EPS) is NOT the market-implied"
            "\n  growth rate. Forward EPS growth measures analyst consensus expectations for NEXT"
            "\n  year's earnings. The reverse DCF implied growth measures what PERPETUAL growth"
            "\n  the market cap assumes at the current price. These are completely different concepts."
            "\n  If your implied growth equals the forward EPS growth, you have made this error."
            "\n  Recompute using the formula above."
            "\n"
            "\nSTEP 2 — COMPARE to historical growth:"
            "\n  - What has revenue grown at over the past 3-5 years (CAGR)?"
            "\n  - What has EPS grown at over the past 3-5 years?"
            "\n"
            "\nSTEP 3 — INTERPRETATION (critical — get the direction right):"
            "\n  • Implied > Historical by >50%: PRICED FOR PERFECTION (e.g., market implies 12%"
            "\n    but actual CAGR is 7%). The market expects more than the company has delivered."
            "\n  • Implied ≈ Historical (within ±30%): REASONABLY PRICED relative to track record."
            "\n  • Implied < Historical: MARKET IS CONSERVATIVE. The company has delivered more growth"
            "\n    than the current price implies. This is a potential undervaluation signal, NOT a red flag."
            "\n  A stock where implied growth is BELOW historical growth is NOT overpriced — the market"
            "\n  is being cautious relative to the company's track record."
            "\n"
            "\nSTEP 4 — PRICE-IN CHECK:"
            "\n  If the stock has returned >50% in 6 months, explicitly ask:"
            "\n  'Has the thesis already been PRICED IN by this move?' A stock that has already"
            "\n  appreciated 80% may have already captured the upside from the catalysts."
            "\n  Conversely, if the stock has DECLINED >20% in 6 months AND implied growth is"
            "\n  below historical growth, the market may be overly pessimistic — flag as potential"
            "\n  undervaluation, NOT 'priced for perfection.'"
            "\n"
            "\n5. Present this in a clear table:"
            "\n| Check | Value |"
            "\n|-------|-------|"
            "\n| Implied FCF Growth (reverse DCF — SHOW FORMULA) | X% |"
            "\n| Verified Implied FCF Growth (from ground-truth data) | X% (copy from verified data — if available, your computed value MUST match within 1pp or you MUST explain the discrepancy) |"
            "\n| Actual Historical Revenue Growth (3-5yr CAGR) | X% |"
            "\n| Actual Historical EPS Growth (3-5yr) | X% |"
            "\n| Growth Gap | Implied minus Actual = +/-X% — (conservative / reasonable / stretched / priced for perfection) |"
            "\n| 6-Month Return | (use VERIFIED value from ground-truth data — do NOT compute your own) |"
            "\n| Is thesis priced in? | YES / PARTIALLY / NO — with explanation |"
            "\n"
            "\nGOLDEN VARIABLE RULE (MANDATORY): If the verified data provides 'Implied FCF Growth"
            " (reverse DCF)' with a numeric value (not N/A), that is the AUTHORITATIVE value."
            " Your own computation MUST use the same TTM FCF input. If your result differs by"
            " >1pp from the verified value, you have used incorrect inputs — reconcile:"
            "\n  a) Check: did you use a different FCF? The verified value uses TTM quarterly sum."
            "\n  b) Check: did you use a different WACC? The verified value uses 10%."
            "\n  c) If you cannot reconcile, USE the verified value and note the discrepancy."
            "\n\nPEER COMPARISON (MANDATORY — use the INDUSTRY PEER COMPARISON data provided):"
            "\nIf peer comparison data is provided, you MUST include a '### Relative Valuation'"
            " section that:"
            "\n1. Names the 3-5 closest peers by market cap and business model."
            "\n2. Compares the target's P/E, Forward P/E, EV/EBITDA, operating margin, and net margin against"
            "   the peer group. Use the ACTUAL peer data provided — do NOT fabricate peer metrics."
            "   For FRANCHISORS (QSR, MCD, YUM): use OPERATING MARGIN for comparison, not net"
            "   margin. Franchise revenue recognition inflates the revenue base with system-wide sales"
            "   that flow through franchisees, making net margin appear artificially low. Operating"
            "   margin isolates the franchisor's actual profitability from its fee-based model."
            "\n3. States whether the target trades at a PREMIUM or DISCOUNT to peers, and by how much."
            "\n4. If the target trades at a premium, justify WHY it deserves it (faster growth,"
            "   better margins, dominant market position) with specific numbers."
            "\n5. If you cannot justify a premium and the target's multiples are above peer median,"
            "   flag it as a RELATIVE OVERVALUATION risk."
            "\n"
            "\nMARGIN GAP DECOMPOSITION (MANDATORY when |Operating Margin − Net Margin| > 10pp):"
            "\nA large gap between operating margin and net margin signals significant below-the-line"
            " charges that are NOT visible in operating income. This gap MUST be investigated:"
            "\n1. DECOMPOSE the gap with SPECIFIC DOLLAR AMOUNTS from the income statement."
            "   You MUST extract the actual figures — naming categories without numbers is NOT"
            "   a decomposition. Use this exact format:"
            "\n   | Below-the-Line Item | Amount | Recurring? |"
            "\n   |---------------------|--------|------------|"
            "\n   | Interest Expense | $XXM | Yes |"
            "\n   | Stock-Based Compensation | $XXM | Yes |"
            "\n   | Impairments / Write-Downs | $XXM | No |"
            "\n   | Restructuring Charges | $XXM | No |"
            "\n   | Other Non-Operating | $XXM | ? |"
            "\n   | **Total Below-the-Line** | **$XXM** | |"
            "\n   The total MUST approximately equal (Op Income − Net Income). If it doesn't, you"
            "   have missed an item. Go back and find it."
            "\n3. If net margin is NEGATIVE while operating margin is POSITIVE, state explicitly:"
            "   'Operations are profitable (X% operating margin) but below-the-line charges erase"
            "   net earnings. The gap is driven by [specific items].'"
            "\n4. CRITICAL for valuation: if the gap is driven by non-recurring items, the company's"
            "   NORMALISED net margin is higher than reported. If driven by recurring items (SBC,"
            "   interest), the operating margin overstates true profitability."
            "\n5. In the peer comparison, compare BOTH operating margin AND net margin. If the"
            "   company has a premium operating margin vs peers but negative net margin, flag"
            "   this contradiction: 'Operating profitability is strong, but net margin anomaly"
            "   must be resolved before using operating margin as a valuation advantage.'"
            "\n"
            "\nPEER RELEVANCE CHECK (MANDATORY — do this BEFORE using peer medians):"
            "\nScan the peer data header for a PEER SIZE MISMATCH or PEER SIZE GAP warning."
            "\n1. If present: the peers are from the same industry classification but are"
            "   STRUCTURALLY DIFFERENT businesses at a much larger scale. State which peers"
            "   were provided and their market caps."
            "\n2. ASSESS BUSINESS MODEL RELEVANCE: Do the named peers actually compete in the"
            "   same market as the target? A $160M video-tech SaaS company has NOTHING in"
            "   common with a $300B enterprise software conglomerate, even if both are classified"
            "   as 'Software - Application.' If no peer operates in the target's specific"
            "   sub-market, state: 'No direct public-market comparables identified in peer data."
            "   Industry classification peers operate at a different scale and in different"
            "   sub-markets. Peer multiples used with HIGH UNCERTAINTY.'"
            "\n3. If median peer market cap is >10x target: peer P/E and EV/EBITDA multiples"
            "   likely include a LARGE-CAP LIQUIDITY PREMIUM. Apply a size discount (typically"
            "   20-40% for micro-caps vs large-caps) or use EV/Revenue instead of P/E for"
            "   cross-size comparison."
            "\n4. Name any peer that IS a genuine business competitor even if not in the"
            "   provided list. If you know of direct competitors (same product market, similar"
            "   revenue scale), mention them and note that they were not available in the data."
            "\n"
            "\n6. Present this as a table:"
            "\n| Metric | Target | Peer Median | Premium/Discount |"
            "\n|--------|--------|-------------|-----------------|"
            "\n| P/E (TTM) | | | +/-X% |"
            "\n| Fwd P/E | | | +/-X% |"
            "\n| EV/EBITDA | | | +/-X% |"
            "\n| Operating Margin | | | (primary metric for franchisors) |"
            "\n| Net Margin | | | (less meaningful for franchisors) |"
            "\n"
            "\nREVENUE GROWTH CONSISTENCY (MANDATORY):"
            "\nIf the verified data includes a REVENUE TREND PROVENANCE section, you MUST:"
            "\n1. Use the verified YoY revenue growth and quarterly revenue figures as your"
            "   primary growth characterisation. Do NOT cite a historical CAGR that exceeds"
            "   the verified 1-year growth rate by more than 2x without explicitly reconciling"
            "   the discrepancy (e.g., 'growth has decelerated from X% 3-year CAGR to Y% YoY')."
            "\n2. If quarterly revenues are flat or declining (sequential QoQ declines for 2+"
            "   quarters), the company is NOT in a growth phase regardless of historical CAGR."
            "   State this explicitly."
            "\n3. FORBIDDEN: citing a multi-year CAGR in a bullish context without noting that"
            "   CURRENT growth is materially lower. This creates a misleading growth narrative."
            "\n4. For revenue projections in DCF or valuation models, use the recent quarterly"
            "   trend or verified YoY rate — NOT a stale CAGR from a prior growth era."
            "\n5. If the verified data shows a GROWTH DECELERATION warning, you must include"
            "   it in your analysis and explain what caused the slowdown."
            "\n6. CAGR WINDOW CONSISTENCY: If the verified data provides multiple windows"
            "   (1yr, 2yr, 3yr), pick ONE as the PRIMARY rate and use it CONSISTENTLY"
            "   throughout your entire report. If you reference a different window, always"
            "   label it with the window (e.g., '3yr CAGR of 2.3%' vs '1yr growth of 1.2%')."
            "   NEVER mix windows without labels — e.g., writing '1.2% growth' in one"
            "   paragraph and '2.3% growth' later without specifying which window is nonsensical."
            "\n"
            "\nCURRENT RATIO ANALYSIS (MANDATORY when CR < 1.0):"
            "\nIf the current ratio is below 1.0, you MUST decompose current liabilities before"
            " concluding it is a risk. Check the verified data for CURRENT LIABILITY DECOMPOSITION:"
            "\n1. What percentage of current liabilities is deferred revenue? For SaaS, subscription,"
            "   and media companies (KLTR, CRM, NOW), deferred revenue is often 30-60% of CL."
            "   This is a contract obligation to deliver services, NOT a cash outflow."
            "\n2. Report the Adjusted Current Ratio (excl. deferred revenue) from verified data."
            "   If adjusted CR >= 1.0, CR < 1.0 is NOT a solvency risk — state this explicitly."
            "\n3. What is the current debt component? If significant, when does it mature?"
            "   Are there revolving credit facilities? This determines whether the company can"
            "   refinance near-term obligations."
            "\n4. What is the cash position relative to current debt? If cash > current debt,"
            "   near-term repayment risk is LOW regardless of the raw CR."
            "\n5. FORBIDDEN: Saying 'current ratio is below optimal levels' or 'below the benchmark"
            "   for current asset coverage' without decomposing WHY it is below 1.0. This is"
            "   the equivalent of citing D/E without checking if equity is thin — it is lazy"
            "   analysis that fails to distinguish between accounting artifacts and real risk."
            "\n6. For SaaS/subscription businesses: a CR < 1.0 driven by deferred revenue is"
            "   actually a POSITIVE signal — it means the company has pre-collected cash for"
            "   future service delivery. The 'liability' represents undelivered value, not"
            "   unpaid bills."
            "\n"
            "\nPEER PREMIUM CONTRADICTION CHECK (MANDATORY after filling the peer table):"
            "\nAfter completing the peer comparison table, run this self-check:"
            "\n1. Count how many metrics show PREMIUM (target > peer median) vs DISCOUNT."
            "\n2. If Forward P/E shows a PREMIUM to peers but you conclude 'undervalued relative"
            "   to peers' elsewhere in the report, this is a CONTRADICTION. The forward earnings"
            "   multiple — what investors actually pay per dollar of expected earnings — shows the"
            "   stock is MORE EXPENSIVE than peers, not less."
            "\n3. To call a stock 'undervalued vs peers' while trading at a forward P/E premium,"
            "   you MUST explain WHICH metric supports undervaluation AND why that metric should"
            "   dominate the forward P/E signal. Generic statements like 'undervalued' without"
            "   specifying the metric are FORBIDDEN."
            "\n4. If Forward P/E is at a premium AND trailing EPS is negative, the premium is"
            "   based on speculative forward earnings. State this explicitly: 'The apparent forward"
            "   P/E premium of X% to peers rests on unproven forward EPS estimates.'"
            "\n5. Present a CONTRADICTION SUMMARY if any pair of metrics conflicts:"
            "\n| Conflict | Metric A says | Metric B says | Resolution |"
            "\n|----------|-------------|-------------|------------|"
            "\n| (e.g.) | Fwd P/E: 19.6 (Premium +48%) | Op Margin: 6% (Discount -40%) | Margin discount does not offset earnings multiple premium because... |"
            "\n"
            "\nSaying a stock is 'undervalued' or 'reasonably priced' without peer context is"
            " analytically empty. Every valuation judgment must be RELATIVE to comparable companies."
            "\n\nMATERIAL DATA GAPS (MANDATORY ESCALATION):"
            "\nIf ANY core financial statement (cash flow, balance sheet, income statement) is"
            " missing or marked [DATA QUALITY: ... UNAVAILABLE], you MUST:"
            "\n1. Flag it prominently in a dedicated '### Material Data Gaps' section at the TOP"
            "   of your report, before any analysis."
            "\n2. Explain WHY the missing data matters for this specific sector/company."
            "   For insurers: operating cash flow is critical because IFRS 17 / GAAP insurance"
            "   accounting makes net income unreliable — cash flow reveals true earnings quality."
            "   For REITs: FFO/AFFO from cash flow is the primary valuation metric."
            "   For all sectors: cash flow is required for DCF valuation."
            "\n3. Cap your confidence at LOW if cash flow data is missing."
            "\n4. Do NOT recommend BUY with missing critical data. The maximum recommendation"
            "   when a core financial statement is unavailable is HOLD, with a note that the"
            "   position should be revisited when complete data becomes available."
            "\n5. Do NOT paper over the gap with phrases like 'despite limited data' or"
            "   'this limitation should be considered' — these are weasel phrases that allow"
            "   the report to proceed as if the gap doesn't matter. It does."            + get_language_instruction(),
        )

        # Pre-fetched data mode: inject data, skip tool round-trips
        if prefetched.get("fundamentals"):
            data_block = (
                "\n\n" + prefetched.get("company_profile", "")
                + "\n\n=== PRE-FETCHED FUNDAMENTALS ===\n"
                + prefetched["fundamentals"]
                + "\n\n=== PRE-FETCHED BALANCE SHEET (Quarterly) ===\n"
                + prefetched.get("balance_sheet", "N/A")
                + "\n\n=== PRE-FETCHED CASH FLOW STATEMENT (Quarterly) ===\n"
                + prefetched.get("cashflow", "N/A")
                + "\n\n=== PRE-FETCHED INCOME STATEMENT (Quarterly) ===\n"
                + prefetched.get("income_statement", "N/A")
                + "\n\n=== INDUSTRY PEER COMPARISON ===\n"
                + prefetched.get("peer_comps", "N/A")
            )
            mode_instruction = (
                "All required fundamental data has been pre-fetched"
                " and is provided below. Analyze the data directly to write your report."
            )
        else:
            data_block = ""
            mode_instruction = (
                "Use the provided tools to progress towards answering the question."
                " If you are unable to fully answer, that's OK; another assistant with different tools"
                " will help where you left off. Execute what you can to make progress."
                f" You have access to the following tools: {', '.join([t.name for t in tools])}."
            )

        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are a helpful AI assistant, collaborating with other assistants."
                    " {mode_instruction}"
                    " If you or any other assistant has the FINAL TRANSACTION PROPOSAL: **BUY/HOLD/SELL** or deliverable,"
                    " prefix your response with FINAL TRANSACTION PROPOSAL: **BUY/HOLD/SELL** so the team knows to stop."
                    "\n{system_message}"
                    "\n\nCRITICAL — TODAY'S TRADING DATE IS {current_date}."
                    " All dates in your report MUST reference this exact date (year, month, day)."
                    " {instrument_context}"
                    "\n\n{verified_data}"
                    "{data_block}",
                ),
                MessagesPlaceholder(variable_name="messages"),
            ]
        )

        prompt = prompt.partial(mode_instruction=mode_instruction)
        prompt = prompt.partial(system_message=system_message)
        prompt = prompt.partial(current_date=current_date)
        prompt = prompt.partial(instrument_context=instrument_context)
        prompt = prompt.partial(
            verified_data=verified_data.replace("{", "{{").replace("}", "}}")
        )
        prompt = prompt.partial(
            data_block=data_block.replace("{", "{{").replace("}", "}}")
        )

        if data_block:
            # Single-shot: all data in prompt, no tools needed
            result = (prompt | llm).invoke(state["messages"])
            return {"fundamentals_report": result.content}

        # Fallback: tool-calling loop
        chain = prompt | llm.bind_tools(tools)

        # Internal tool loop — runs tool calls locally for parallel execution
        tool_map = {tool.name: tool for tool in tools}
        local_messages = list(state["messages"])

        for _ in range(10):
            result = chain.invoke(local_messages)
            if not result.tool_calls:
                return {"fundamentals_report": result.content}
            local_messages.append(result)
            for tc in result.tool_calls:
                try:
                    tool_output = tool_map[tc["name"]].invoke(tc["args"])
                except Exception as e:
                    tool_output = f"Error: {e}"
                local_messages.append(
                    ToolMessage(content=str(tool_output), tool_call_id=tc["id"])
                )

        return {"fundamentals_report": result.content or ""}

    return fundamentals_analyst_node
